# Numpy - Library to handle arrays.
- statically typed (element types can't be mixed or altered)
- non resizeable (can't append or remove elements)
- much faster than python's dynamically typed lists
- supports use of vector operations
- 



## Create arrays

In [7]:
import numpy as np

my_array = np.array([5, 2, 6, 8]) # my_array = np.array([5, 2, 6, 8, dtype=float]) om man specifikt vill sätta datatypen själv.
my_array.dtype


dtype('int32')

In [3]:
my_list = [5, True, "Hello"]
print(my_list[2] + "!")

Hello!


In [14]:
a2 = np.random.random(20)
a3 = np.random.randint(10, 20, 20) # sista specifierar storlek på array
a3


array([15, 10, 11, 19, 11, 13, 10, 19, 14, 17, 12, 15, 18, 14, 19, 15, 18,
       16, 17, 17])

In [16]:
a4 = np.zeros(10)
a4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a5 = np.ones(10)
a5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
a6 = np.linspace(0, 10, 100)
a6

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [23]:
a7 = np.arange(0, 10, 0.1)
a7

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])